/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iAttestationStationSol from "./IAttestationStation.sol";
export type { iAttestationStationSol };
