/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as hackthonAttestationSol from "./HackthonAttestation.sol";
export * as utils from "./utils";
export { AttestationStation__factory } from "./AttestationStation__factory";
