/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as hackthonAttestationSol from "./HackthonAttestation.sol";
export type { hackthonAttestationSol };
import type * as utils from "./utils";
export type { utils };
export type { AttestationStation } from "./AttestationStation";
