/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AttestationStation__factory } from "./AttestationStation__factory";
export { IAttestationStation__factory } from "./IAttestationStation__factory";
